### ISSUE TITLE
Tests failing due to missing test modules

### ISSUE THREAD

**Issue by carlsmedstad** [simonrob/pyasyncore#4]
Hey :wave:

I'm in the process of packaging this for Arch Linux and noticed that the tests are missing some of the modules required to run: 

```sh
$ python -m unittest discover -v
tests.test_asyncore (unittest.loader._FailedTest.tests.test_asyncore) ... ERROR

======================================================================
ERROR: tests.test_asyncore (unittest.loader._FailedTest.tests.test_asyncore)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_asyncore
Traceback (most recent call last):
  File "/usr/lib/python3.12/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/build/python-pyasyncore/src/pyasyncore-1.0.4/tests/test_asyncore.py", line 11, in <module>
    from test import support
ModuleNotFoundError: No module named 'test'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by simonrob** [comment]
The [`test`](https://docs.python.org/3/library/test.html) module is part of the standard library. I suspect this is a platform-specific issue like [the one you experienced with pyasynchat](https://github.com/simonrob/pyasynchat/issues/1)?

**Comment by carlsmedstad** [comment]
Yep, it's the same issue. Sorry for the noise!
